export const initialLocation = {
  city: 'Tel Aviv',
  lat: 32.109333,
  lon: 34.855499,
  set: true,
};

export const initialForecast = {
  lat: null,
  lon: null,
  timezone: '',
  timezone_offset: null,
  current: {
    dt: 1,
    sunrise: null,
    sunset: null,
    temp: null,
    feels_like: null,
    pressure: null,
    humidity: null,
    dew_point: null,
    uvi: null,
    clouds: null,
    visibility: null,
    wind_speed: null,
    wind_deg: null,
    weather: [
      {
        id: null,
        main: '',
        description: '',
        icon: '',
      },
    ],
  },
  hourly: [
    {
      dt: 2,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
    {
      dt: 3,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
    {
      dt: 4,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
    {
      dt: 5,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
    {
      dt: 6,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
    {
      dt: 7,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
    {
      dt: 8,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
    {
      dt: 9,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
    {
      dt: 10,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
    {
      dt: 11,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
    {
      dt: 12,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
    {
      dt: 13,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
    {
      dt: 14,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
    {
      dt: 15,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
    {
      dt: 16,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
    {
      dt: 17,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
    {
      dt: 18,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
    {
      dt: 19,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
    {
      dt: 20,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
    {
      dt: 21,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
    {
      dt: 22,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
    {
      dt: 23,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
    {
      dt: 24,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
    {
      dt: 25,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
    {
      dt: 26,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
    {
      dt: 27,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
    {
      dt: 28,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
    {
      dt: 29,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
    {
      dt: 30,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
    {
      dt: 31,
      temp: null,
      feels_like: null,
      pressure: null,
      humidity: null,
      dew_point: null,
      uvi: null,
      clouds: null,
      visibility: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      pop: null,
    },
  ],
  daily: [
    {
      dt: 32,
      sunrise: null,
      sunset: null,
      temp: {
        day: null,
        min: null,
        max: null,
        night: null,
        eve: null,
        morn: null,
      },
      feels_like: {
        day: null,
        night: null,
        eve: null,
        morn: null,
      },
      pressure: null,
      humidity: null,
      dew_point: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      clouds: null,
      pop: null,
      rain: null,
      uvi: null,
    },
    {
      dt: 33,
      sunrise: null,
      sunset: null,
      temp: {
        day: null,
        min: null,
        max: null,
        night: null,
        eve: null,
        morn: null,
      },
      feels_like: {
        day: null,
        night: null,
        eve: null,
        morn: null,
      },
      pressure: null,
      humidity: null,
      dew_point: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      clouds: null,
      pop: null,
      rain: null,
      uvi: null,
    },
    {
      dt: 34,
      sunrise: null,
      sunset: null,
      temp: {
        day: null,
        min: null,
        max: null,
        night: null,
        eve: null,
        morn: null,
      },
      feels_like: {
        day: null,
        night: null,
        eve: null,
        morn: null,
      },
      pressure: null,
      humidity: null,
      dew_point: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      clouds: null,
      pop: null,
      rain: null,
      uvi: null,
    },
    {
      dt: 35,
      sunrise: null,
      sunset: null,
      temp: {
        day: null,
        min: null,
        max: null,
        night: null,
        eve: null,
        morn: null,
      },
      feels_like: {
        day: null,
        night: null,
        eve: null,
        morn: null,
      },
      pressure: null,
      humidity: null,
      dew_point: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      clouds: null,
      pop: null,
      rain: null,
      uvi: null,
    },
    {
      dt: 36,
      sunrise: null,
      sunset: null,
      temp: {
        day: null,
        min: null,
        max: null,
        night: null,
        eve: null,
        morn: null,
      },
      feels_like: {
        day: null,
        night: null,
        eve: null,
        morn: null,
      },
      pressure: null,
      humidity: null,
      dew_point: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      clouds: null,
      pop: null,
      rain: null,
      uvi: null,
    },
    {
      dt: 37,
      sunrise: null,
      sunset: null,
      temp: {
        day: null,
        min: null,
        max: null,
        night: null,
        eve: null,
        morn: null,
      },
      feels_like: {
        day: null,
        night: null,
        eve: null,
        morn: null,
      },
      pressure: null,
      humidity: null,
      dew_point: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      clouds: null,
      pop: null,
      rain: null,
      uvi: null,
    },
    {
      dt: 38,
      sunrise: null,
      sunset: null,
      temp: {
        day: null,
        min: null,
        max: null,
        night: null,
        eve: null,
        morn: null,
      },
      feels_like: {
        day: null,
        night: null,
        eve: null,
        morn: null,
      },
      pressure: null,
      humidity: null,
      dew_point: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      clouds: null,
      pop: null,
      rain: null,
      uvi: null,
    },
    {
      dt: 39,
      sunrise: null,
      sunset: null,
      temp: {
        day: null,
        min: null,
        max: null,
        night: null,
        eve: null,
        morn: null,
      },
      feels_like: {
        day: null,
        night: null,
        eve: null,
        morn: null,
      },
      pressure: null,
      humidity: null,
      dew_point: null,
      wind_speed: null,
      wind_deg: null,
      weather: [
        {
          id: null,
          main: '',
          description: '',
          icon: '',
        },
      ],
      clouds: null,
      pop: null,
      rain: null,
      uvi: null,
    },
  ],
};
